version: 0.0
os: linux
files:
  - source: ./server.js
    destination: /home/ubuntu/nodejs
  - source: ./package.json
    destination: /home/ubuntu/nodejs
hooks:
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 1000
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
